### ISSUE TITLE
No such file or directory: 'mae_pvt.pth'

### ISSUE THREAD

**Issue by VariableXX** [Alvin0629/TransFlow#4]
The error had been occur: 
Traceback (most recent call last):
  File "D:\python_code\optical_flow_est\TransFlow-main\train_flow.py", line 197, in <module>
    train(cfg)
  File "D:\python_code\optical_flow_est\TransFlow-main\train_flow.py", line 71, in train
    model = nn.DataParallel(build_transformer(cfg), device_ids=args.gpus)
  File "D:\python_code\optical_flow_est\TransFlow-main\core\Transflow\__init__.py", line 9, in build_transformer
    return Transflow(cfg[name])
  File "D:\python_code\optical_flow_est\TransFlow-main\core\Transflow\transformer.py", line 18, in __init__
    self.encoder = Encoder(cfg)
  File "D:\python_code\optical_flow_est\TransFlow-main\core\Transflow\encoder.py", line 308, in __init__
    self.feat_encoder.load_state_dict(torch.load("mae_pvt.pth", map_location='cpu'), strict=False)
  File "D:\ProgramData\Miniconda3\envs\mmdet\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\ProgramData\Miniconda3\envs\mmdet\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\ProgramData\Miniconda3\envs\mmdet\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'mae_pvt.pth'

**Comment by Alvin0629** [comment]
Thank you for the question. Yes, it needs to be downloaded first and put it under root/.
